version: "3.9"
services:
  training:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash scripts/run_training.sh
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  prediction:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash scripts/run_server.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  mlflow:
    image: mlflow/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow/tracking:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
