stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw_data.csv
    outs:
      - data/processed_data.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed_data.csv
      - params.yaml
    outs:
      - artifacts/models
