FROM python:3.9-slim

# Installer des dépendances système
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential curl && \
    rm -rf /var/lib/apt/lists/*

# Installer MLflow et d'autres dépendances
RUN pip install --no-cache-dir mlflow[extras] boto3 psycopg2-binary

# Exposer le port pour le serveur MLflow
EXPOSE 5000

# Définir le répertoire de travail
WORKDIR /mlflow

# Commande par défaut pour exécuter MLflow
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
